* 填空题

操作系统具有 #并发,共享性,虚拟性,异步(不确定性)# 四种特性

常用的预防"抖动"的方法有 #采用局部置换策略# ,把工作集算法融入到处理机调度中, #挂起若干进程# 和利用"L=S"准则调度缺页率四种

磁盘空间可以分为文件区和 #对换区# 两部分,对文件区的管理采用 #离散# 分配方式
(对换区 连续分配方式)

缺页率受到 =分配给作业的主存块数(多则低) - 物理块,页面的大小(页面大则低),程序编制方法,页面调度算法 = 四个因素影响

磁盘的访问时间可以分为以下三个部分 #寻道时间,旋转延迟时间,传输时间#

目前常用的外存组织方式有连续组织方式 #链接组织方式# 和 #索引组织方式#

描述进程之间执行先后顺序的有向无循环图,也叫 #前趋图#

进程的三种基本形态包括 #运行,就绪,阻塞#
(创建,结束)

虚拟存储器的特征有 #多次性,对换性,虚拟性#
(离散性)

文件按用途可以分为 #系统文件,用户文件,库文件#

外存的链接组织形式可以分为 #显式链接,隐式链接#

分页存储管理中联想存储器又叫做 #快表#

程序的链接分为 #静态链接,装入时动态链接,运行时动态链接#

操作系统的基本类型有 #批处理操作系统,分时操作系统,实时操作系统#

在采用时间片轮转调度算法的分时系统中,当用户数为100时,为保证响应时间不超过2秒,此时时间片最大应为 #20ms#

程序经编译或汇编以后形成的目标程序,其指令的顺序都是以零作参考地址,这些地址称为 #逻辑地址#

请求页面分页操作系统在基本分页的系统的基础上,增加了 #请求调页功能# 和 #页面置换功能# 所形成的页式虚拟存储系统

主存储器与外围设备之间的数据传送控制方式有 #程序直接控制,中断驱动方式,DMA方式,通道控制方式#

为实现设备的独立性,系统必须设置一张 #逻辑设备表(LUT)# 将用于应用程序中所使用的逻辑设备名映射为物理设备名

文件的物理结构分为 #顺序文件,索引文件,索引顺序文件#

UNIX的文件系统空闲空间的管理是采用 #成组链接法#

在一个分页式存储管理系统中,页表的内容如下,若页面大小为4k,则地址转换机构将对应地址0转换成的物理地址是 #8192#
| 页号 | 块号 |
|    0 |    2 |
|    1 |    1 |
|    2 |    7 |

I/O设备可以按信息交换的单位分为字符设备和 #块设备#

如果利用30行, 40列的位示图来标志空闲盘块的状态,在进行盘块分配时,当第一次找到的空闲盘块(即该位置为0)处于第11行,第18列,则相应的盘块号为 #418#

#并发# 和共享是操作系统的两个最基本的特征,它们又是互为存在的条件

#缓冲# 可以有效地缓解CPU与I/O设备速度不匹配的矛盾

进程实体由程序段,相关数据段和 #进程控制块(PCB)# 三部分构成

进程的三种基本状态是 #就绪,执行,阻塞#

所谓"管道"是指用于连接一个读进程和一个写进程以实现他们之间通信的一个共享 #文件#

在装入时对目标程序中指令和数据地址的修改过程称为 #重定位#

在采用分页存储管理的系统中,页面大小为1KB,如果逻辑地址为2175B,则页号为 #2# ,页内地址为 #127#


与传统的存储器管理方式比较,虚拟存储器有以下三个重要特征 #多次性,对换性,虚拟性#

文件系统管理的对象有文件, #目录# , 和磁盘存储空间

根据文件组织的方式, 可以把结构文件分为顺序文件,引索文件和 #引索顺序文件#



* 判断题
[T] 推动分时系统形成和发展的主要动力是为了满足用户对人机交互的需求

[T] 处于执行状态下的进程,可以转换成就绪状态,阻塞状态和终止态

[T] 进程控制块PCB是一个数据结构

[T] 银行家算法可以用于避免死锁的产生

[T] 在分段系统中,用户程序的地址空间是二维的

[F] 在内存的动态分区管理方式中,回收内存时空闲分区的个数一定会增加

[F] 直接存储器访问方式中,数据传输的基本单位是字节

[F] 目录管理中系统不允许不同用户对不同文件采用相同的名字

[F] 采用连续组织方式管理磁盘空间,事先不必知道文件的长度

[F] 假脱机技术可以将物理CPU虚拟为多台逻辑CPU,从而允许多个用户共享一台主机

-----

[F] 多通道批处理系统允许多个程序同时执行
(只是同一批次调入内存,放在内存不同部分,当一个作业由等待输入操作而让处理机空闲.系统自动切换处理另一个作业)

[F] 线程是资源分配的最小单位
(进程)

[T] 进程的创建必须申请一个空白的PCB

[F] 整型型号量满足同步机制遵循的四个基本原则是最常用的进程同步控制方式

[F] 为预防死锁,我们需谨慎的分配资源,保障系统处于安全状态

[F] 分页存储管理中页面大小可以任意设置

[F] 进程的状态可以是相互转换的,"执行"到"阻塞","阻塞"到"执行"

[T] 分段存储管理比分页存储管理更容易实现信息的保护

[T] 一个进程可以有多个线程,一个线程也可以有多个子线程

[F] 虚拟存储器的大小受到内存,外存的限制,因此,外存越大,虚拟内存空间可以设置得越大

[F] 磁盘扫描算法中,FCFS算法会导致进程"饥饿"现象,而SCAN算法可以防止此现象的发生

[T] Spooling 系统实现了虚拟设备功能

[F] 相对路径是从根目录开始到达指定文件或目录的唯一通路

[F] 分段存储管理中段的划分是在程序编译时系统自动设置的

[F] 用户线程可以被内核感知

-----

[F] 操作系统是系统软件的一种,在进行系统安装时可以先安装其他软件,然后再装操作系统

[F] 并发性是指若干事件在同一时刻发生

[T] 对临界资源应该采取互斥访问方式在实现共享

[T] 原语是一种不可分割操作

[F] 线程是最小拥有资源的单位

[T] 管道是指用于连接一个读进程和一个写进程以实现他们之间的通信的一个共享文件

[T] 假定系统有10台磁带机, 进程p1,p2,p3分别要求9台,3台和8台.假设在T0时刻,进程p1,p2,p3分别获得2台,2台,4台,尚有2台空闲,则T0时刻系统是安全的

[T] 长程调度主要用于多道批处理系统中,而在分时和实时系统中不设置

[F] 新创建一个进程时,将把它所需要的所有资源分配给它,因此可以立即投入运行

[T] 树型目录结构能够解决文件重名问题

[T] 通道一旦被启用就能独立CPU运行,这样可以使CPU和通道并行操作

[F] 页式管理比段式管理更易于实现不同进程之间的信息共享

[T] 缓冲技术可以改善中央处理器与外围设备之间速度不匹配的矛盾

[F] 位示图是一种磁盘调度算法

[T] 在利用符号链接方式实现文件共享时,只是文件主才拥有指向其索引节点的指针

-----

[F] 操作系统中的并发是指两个或多个事件在同一时刻发生

[T] 实时操作系统是指系统能及时响应外部事件的请求,在规定的时间内完成对该事件的处理,并控制所有的实时任务协调一致的运行

[F] 操作系统中所谓"虚拟"是指,通过某种技术把一个物理实体变为若干个物理实体

[T] 原语是由若干条机器指令所构成,用以完成特定功能的一段程序,原语在执行期间是不可分割的或不可中断的

[F] 进程是拥有资源的基本单位,管程是调度的基本单位

[F] 银行家算法是一种预防死锁的方法
(是一种避免死锁的著名算法)

[T] 动态运行时装入方式在把装入模块装入内存后, 并不立即吧装入模块中的相对地址转化为绝对地址,而是把这种地址转换推迟到程序真正要执行的时候

[F] 虚拟存储器是一种能从物理上对内存容量加以扩充的存储器系统

[T] 在页面置换算法中,最佳置换算法有最好的性能,但实际无法实现的

[F] 磁盘和打印机都是块设备




* 选择题
作业提交系统到作业完成的时间间隔称为 #周转时间#

所谓动态重定位.地址变换是发生在 #程序执行时#

下面最有可能使得高地址空间成为最大空闲的分配算法是 #首次适应算法#

下名关于虚拟存储器的叙述中,正确的是 #要求程序运行前必须全部装入内存且在运行过程中一直驻留内存#

一个页式存储管理的系统中,逻辑地址3654,页的大小为1K,那么该逻辑地址的页号和页内地址是 #3,582#

按设备的共享属性分类可以分为 #独占设备,共享设备,虚拟设备#

直接数据传输DMA方式是 #设备和主存储器直接传输数据#

CPU输出数据的速度远远高于打印机的打印速度,为解决这一矛盾采用 #缓冲#

利用SpooLing技术实现虚拟设备的目的是 #把独享的设备变为可以共享的#

UNIX的引索表直接包含在文件引索节点中,索引表共13个表项,10个用于直接寻址方式,其余三个分别用于一级,二级,三级缓存寻址方式,假定一个物理块的大小为1KB,索引表中每个表项占4个字节,那么文件大小不超过多少时,可以组成直接寻址文件
#10KB#

C临界区是指 #访问临界资源的一段代码#

D进程所请求求的一次打印输出结束后将使进程状态从 #阻塞态变成就绪态#

A段页式存储管理汲取了页式管理和段式管理的长处,其实现原理结合了页式和段式管理的基本思想,即 #用分段方法来分配和管理用户地址空间,用分页方法来管理物理存储空间#

B若一个系统内存有64M,处理器是32位地址,则它的虚拟地址空间为 #4GB# 字节

C假定盘块的大小为1K,对于1.2MB的软盘,在FAT12文件系统下,FAT表需要占用 #1.8k# 的存储空间
(1.2MB/1KB*1.5byte = 1.8KB) 12bit = 1.5byte

D在操作系统中,用户在使用I/O设备,通常采用 #逻辑设备名#

A操作系统采用缓冲技术,能减少对CPU的 #中断#

B文件目录的最基本功能是 #按名存取#

C若系统中有五台绘图仪, 有多个进程均需要使用两台,规定每个进程一次仅允许申请一台, 则至多允许 #4# 个进程参与竞争,而不会发生死锁

D在现代操作系统中采用缓冲技术的主要目的是 #提高CPU个I/O设备之间的并行性#

-----

C 下面不属于操作系统目标的描述是 #虚拟性#

B 对磁盘I/O控制采用 ## 方式

B 高级调度的主要功能是从处于 #后备# 状态的队列中选择适当的作业调入内存

A 下列描述正确的是 #进程的阻塞是当条件不满足时,由进程自己调用Block原语把自己阻塞起来#

B 一台计算机系统,内存2GB, 硬盘大小 500GB, 安装了 64位操作系统,请问其虚拟内存空间大小是多少 #500G+2G#

B 就绪状态进程被挂起,状态将变为 #静止就绪#

C 某个信号量s的初值为2,当前值为-3,采用记录型信号量控制,在该信号量的进程数为 #3# 个

D 下面对进程死锁描述错误的是 #只要不出现资源竞争,系统就不会出现死锁#

A 页面大小为1000, 设基地址寄存器的内存为2000, 在采用动态重定位的系统中,当执行指令 "LOAD X, 2500"时,操作数的物理地址是 #2500#

B 要求在规定的时间内对外界的请求必须给予相应的OS是 #实时系统#

A 磁带机属于 #顺序存取# 设备

A 时间片轮转法进行进程调度是为了 #多个终端都能得到系统的及时响应#

A 采用段页式存储管理中, 若地址用32位表示 ,其中20位表示段号,则允许每段的最大长度是 #2^12#

D 下列对线程的描述正确的是 #线程可以并发执行#

C 从就绪队列选择一个进程,使其获得处理机,属于 #进程调度#

-----

C 一个正在CPU上运行的进程,其进程状态 #可以转变为就绪状态,也可以转变为阻塞状态#

B 同一系统中进程之间即相互依赖又相互制约,如果两个进程同时要用一台打印机,其中一个进程必须等待,这种关系称为 #互斥#

D 对应资源编号, 要求进程按照序号顺序申请资源,是破坏死锁比必要条件中的那一条? #循环等待#

B 设有n个进程使用同一个共享变量,如果最多允许m (m < n) 个进程同时进入相关临界区,则信号量的变化范围是 #m,m-1,m-2,......,1,0,-1,...,m-n#

B 既考虑作业等待时间,又考虑作业执行时间的调度算法是 #高响应比优先#

A 从作业提交系统到作业完成的时间间隔称为 #周转时间#

B 所谓动态重定位,地址变换是发生在 #程序执行时#

A 下面最有可能使高地址空间成为最大空闲分区的分配算法是 #首次适应法#

B 在下面关于虚拟存储器叙述中,正确的是 #要求程序运行前不必全部装入内存且在运行过程中不必一直驻留在内存#

A

D

A

C

A

C

-----

A 下面哪一个不是分时系统的基本特征 #同时性#

B 下面关于进程状态转换的说法中错误的是 #可以由就绪态转换为阻塞态#

D 下面哪项不是进程控制块中保护的信息? #进程代码#

A 决定把外存上处于后备队列中的那些作业调入内存,并为他们创建进程,分配必要的资源,排在就绪队列上 属于哪种调度的任务 #高级调度#

D 下面说法, 错误的是 #平均周转时间短是分时操作系统中选择进程调度算法的重要准则#

C 下面那个属于实时调度算法? #最早截止时间优先调度算法#

C 下列说法中错误的是 #采用装入时动态链接方式,凡在执行过程中,未被用到的目标模块都不会被调入内存和被链接到装入模块上#

A 下面关于分页存储管理方式,和分段存储管理方式说法中错误的是 #分段存储管理方式比分页存储管理方式更利于信息共享#

C 下面哪项不属于I/O系统的基本功能 #提高主存储器利用率#

B 按照数据存取和传输单位分类,设备可以分为 #块设备和字符设备#


* 名词解释
*** 局部性原理
(1)程序在执行时呈现局部性规律
(2)在一较短时间内,程序的执行仅局限于某个部分
(3)相应的,所访问的存储空间局限于某个区域

*** 低级调度
(1)低级调度又称进程调度,短程调度,
(2)它决定就绪队列中哪个进程将获得处理机,
(3)然后由分派程序执行把处理机分配给该进程的操作

*** 延迟写
(1)延迟写是指缓冲区A中的数据本应该立即写回磁盘,但考虑到该缓存区的数据可能在不久之后再被本进程或其他进程访问,因而并不理解将该缓冲区A中的数据写入磁盘,而是将它挂在空闲缓冲区队列末尾
(2)当有进程申请到该缓冲区时,才将该缓冲区中的数据写入磁盘

*** 中级调度
(1)按照给定的原则和策略,将外存交换区中的进程调入内存,把内存中的非执行进程交换到外存交换区
(2)中级调度时存储器管理中的对换功能

*** 设备独立性
(1)设备独立性即在应用程序中所使用的设备,不局限于使用某个具体物理设备
(2)应用程序用逻辑设备名称来请求使用某类设备.系统在执行时,使用物理设备名称

*** 临界区
(1)一个程序片段的集合,这些程序片段分散在不同的进程中,对某个共享的数据结构(共享资源)进行操作
(2)进程中涉及到临界资源的程序段叫做临界区

*** 管程
(1)管程定义了一个数据结构和能为并发进程在该数据结构上所执行的一组操作,这组操作能同步进程和改变管程中的数据
(2)管程由局部与管程的共享变量说明,对该数据结构进行操作的一组过程以及局部于管程的数据初始化语句

*** 通道(I/O处理机)
(1)通道是独立于CPU的专门负责数据输入/输出传输工作的处理机
(2)对外部设备实现统一管理,代替CPU对输入/输出操作进行控制,从而使输入输出操作可以与CPU并行操作

*** 进程控制块(PCB)
(1)系统为管理进程设置的一个专门的数据结构,用它来记录进程的外部特征,描述进程变化过程
(2)系统利用PCB来控制和管理进程,所以PCB是系统感知进程存在的唯一标志.进程与PCB是一一对应的

*** 虚拟存储器
(1)所谓虚拟存储器,是指具有请求调入功能和置换功能
(2)能从逻辑上对内存容量加以扩充的一种存储器系统

*** 死锁
(1)指多个进程因竞争资源而造成的一种僵局
(2)若无外力作用,这些进程将永远不能再向前推进

*** 对换
(1)所谓"对换",是指把内存中暂不能运行的进程或者暂时不用的程序和数据换出到外存上,以便腾出足够的内存空间
(2)再把已具备运行条件的进程或者进程所需要的程序和数据换入内存





* 简答题与计算题
  *** 从调度性,并发性,拥有资源及系统开销方面对进程和线程进行比较
(1)调度方面.在引进线程之前,进程是调度和分派的基本单位,每次被调度时都需要进行上下文切换,开销较大.引进线程后,线程是调度和分派的基本单位.当线程切换时,仅需保存和设置少量寄存器内容,切换代价远低于进程.
(2)并发性方面,在引入线程的OS中,不仅进程之间可以并发执行,而在一个进程中的多个线程之间亦可并发执行
(3)拥有资源方面,进程可以拥有资源,并作为一个操作系统拥有资源的一个基本单位,线程本身不具备系统资源,而是仅有一点必不可少的,能保证独立运行的资源,多个线程共享进程所拥有的资源
(4)系统开销方面,线程创建,撤销,切换,同步和通信时所付出的开销都小于进程对应操作的开销

*** 何谓用户级线程和内核支持级线程
(1)用户级线程是在用户空间中实现,对线程创建,撤销,同步和通信功能,都无需内核的支持,即用户线程与内核无关,内核完全不知道用户级线程的存在
(2)内核支持线程是在内核的支持下运行的,他们的创建,阻塞,撤销,切换等,也都是在内核空间实现的.为了对内核线程的控制和管理,在内核空间也为每一个内核线程设置一个线程控制块,内核根据该控制块而感知某线程的存在,并对其加以控制

*** 在请求分页管理系统中,产生抖动的原因是什么
(1)产生抖动的原因是,同时在系统运行的进程太多
(2)由此分配给没每一个进程的物理块太少,不能满足程序正常执行的基本要求,致使每个进程在运行的时候,频繁的抛出缺页,必须请求系统将所缺页调入内存
(3)这会使得在系统中排队等待页面调入/调出的进程数目增加.显然,对磁盘的有效访问时间也随之急剧增加,造成每个进程的大部分时间都用于页面的调入/调出,而几乎不能再去做任何有效的工作,从而导致处理机的利用率急剧下降并趋于0的情况,此时的进程是处于"抖动"状态

*** 试说明设备驱动程序具有那些特点
(1)是请求I/O进程与设备控制器之间的一个通讯程序
(2)驱动程序与I/O设备的特性紧密相连
(3)驱动程序与I/O控制方式紧密相关
(4)驱动程序与硬件紧密相关
(5)部分程序由汇编语言书写,基本部分往往固化在ROM中

*** 在银行家算法中,若出现下述资源分配情况试问:
| Process | Allocation | Need | Available |
| P0      |       0022 | 0012 |      1612 |
| P1      |       1030 | 1230 |           |
| P2      |       1000 | 3657 |           |
| P3      |       1303 | 2356 |           |
| P4      |       0002 | 0652 |           |

(1)该状态是否安全?若安全给出一个安全序列

| Process | Allocation | Need | Available | (Finally)=Allocation+Available | order |
| P0      |       0022 | 0012 |      1612 |                           1634 |     1 |
| P1      |       1030 | 1230 |      1634 |                           2664 |     2 |
| P2      |       1000 | 3657 |      3909 |                           4909 |     5 |
| P3      |       1303 | 2356 |      2666 |                           3909 |     4 |
| P4      |       0002 | 0652 |      2664 |                           2666 |     3 |
P0 -> P1 -> P4 -> P3 -> P5

(2)若进程P3提出请求(1,2,0,0)后,系统能否将资源分配给它,若能分配,给出一个安全序列

| Process | Allocation | Need | Available | (Finally) | order |
| P0      |       0022 | 0012 |      1612 |      1634 |     1 |
| P1      |       1030 | 1230 |      2937 |      3967 |     3 |
| P2      |       1000 | 3657 |      3969 |      4969 |     5 |
| P3      |       1303 | 1200 |      1634 |      2937 |     2 |
| P4      |       0002 | 0652 |      3967 |      3969 |     4 |

P0 -> P3 -> P1 -> P4 -> P5

*** 作业A的页表如下所示

| 页号 | 块号 | 状态位 | 访问位 | 修改位 |
|    0 |    6 |      1 |      1 |      1 |
|    1 |    4 |      1 |      0 |      0 |
|    2 |    5 |      1 |      1 |      0 |
|    3 |      |      0 |      0 |      0 |

(1)指出页表中状态位,访问位,修改位的含义?
状态位表示对应的页已经调入内存
访问位表示该页面在一段时间内被访问的次数
修改位表示该页面调入内存后是否被修改

(2)逻辑地址 1800B,对应的物理地址是多少?
P = INT(1800B/1024B) = 1,
d = 1800B mod 1024B = 776
对应的物理块为4, 物理地址 4*1024B + 776 = 4872B

(3)当执行到逻辑地址为 3600B时,会发生什么现象?
P = INT(3600B/1024B) = 3 , 3页面还没有调入内存,产生缺页中断


*** 某个银行提供一个服务窗口和10个供顾客等待的座位.顾客到达银行时,如果有空座位,才允许到取号机上取一个号,等待叫号,取号机每次仅允许一个顾客使用,当营业员空闲通过叫号机选取一位顾客.客和营业员的活动过程描述如下:

#+BEGIN_SRC c
  cobegin {
      process 顾客{
          从取号机获得一个号码;
          等待叫号;
          获得服务;
      }

      process 营业员{
          while(true){
              叫号;
              为顾客服务;
          }
      }
  }coend
#+END_SRC

请添加必要的信号量和 P,V(或者wait(),signal())操作实现上述过程中的互斥与同步.要求写出完整过程,说明信号量的含义并赋予初值

#+BEGIN_SRC c
  cobegin {
      Semaphore seats = 10;
      Semaphore mutex = 1;
      Semaphore custom = 0;
      process 顾客{
          P(seats);
          P(mutex);
          从取号机获得一个号码;
          V(mutex);
          V(custom); //发送信号表示有顾客
          等待叫号;
          V(seats);
          获得服务;
      }

      process 营业员{
          while(true){
              叫号;
              为顾客服务;
          }
      }
  }coend
#+END_SRC
P 表示通过
V 表示释放
当通过PV 实现进程同步的时候,
P 测试消息是否到达
V 操作发生消息

*** 什么叫紧凑? 为什么要进行紧凑?
(1)为了解决碎片问题,可采用的一种方法是,将内存中的所有作业进行移动,使它们相邻接
(2)原来分散的多个小分区便拼接成一个大分区,从而就可以把作业装入运行,这种通过移动把的多个小分区拼凑成大分区进行紧凑的目的是为了提高内存的利用率

*** 什么是死锁?原因是?产生死锁的条件是?解决死锁的办法有?
(1)死锁是指多个进程因进程竞争资源而造成的一种僵局,若无外力作用,这些进程将永远不能再向前推进.产生思索的原因可归结为两点,竞争资源,进程推进顺序非法.
(2)在具备下述四个条件的时候,就会产生死锁.互斥条件,请求和保持条件,不剥夺条件,环路等待条件
(3)银行家算法,安全序列

*** 什么是请求分页系统?它需要那些方面的硬件机构支持?
(1)请求分页系统是在分页系统的基础上,增加了请求调页功能,页面置换功能所形成的页式虚拟存储系统
(2)为了实现请求调页和置换功能,系统必须提供必要的硬件支持.其中,最重要的是:请求分页的页表机制,缺页中断机构,地址变换机构


*** 在一个单批道处理系统中,一组作业的提交时间和运行时间如下表
|    | 作业提交 | 时间运行时间 |
| J1 |     8:00 |          1.0 |
| J2 |     8:50 |         0.50 |
| J3 |     9:00 |         0.20 |
| J4 |     9:10 |         0.10 |

*** 试计算以下三种作业调度算法的平均周转时间和平均带权周转时间:先来先服务;短作业优先;响应比高优先
先来先服务(FCFS):
|    | 作业提交 | 时间运行时间 | 完成时间 | 周转时间 | 带权      |
| J1 |     8:00 |          1.0 |     9:00 | 1.0      | 1/1       |
| J2 |     8:50 |         0.50 |     9:30 | 40/60    | 2/3/0.5   |
| J3 |     9:00 |         0.20 |     9:42 | 42/60    | 42/60/0.2 |
| J4 |     9:10 |         0.10 |     9:48 | 38/60    | 38/60/0.1 |
#+BEGIN_SRC emacs-lisp
  (/ 2 3 0.5)
  (/ 42 60 0.2)
#+END_SRC

T = (1.0 + 0.67 + 0.7 + 0.63)/4 = 0.75
W = (1.0 + 1.34 + 3.5 + 6.3)/4 = 3.035


短作业优先(SJF)

|    | 作业提交 | 时间运行时间 | 完成时间 | 周转时间 | 带权      |
| J1 |     8:00 |          1.0 |     9:00 | 1.0      | 1/1       |
| J2 |     8:50 |         0.50 |     9:48 | 58/60    | 58/60/0.5 |
| J3 |     9:00 |         0.20 |     9:12 | 12/60    | 12/60/0.2 |
| J4 |     9:10 |         0.10 |     9:18 | 8/60     | 8/60/0.1  |
#+BEGIN_SRC emacs-lisp
  (/ 58 60 1.0)
  (/ 12 60 1.0)
  (/ 8 60 1.0)
  (/ (+ 1.0 0.96 0.2 0.13) 4)

  (/ 58 60 0.5)
#+END_SRC

T = (1.0 + 0.96 + 0.2 + 0.13) /4 = 0.5725
W = (1.0 + 1.94 + 1 + 1.3) /4 = 1.31

高响应算法
响应比 = (要求服务时间 + 等待时间)/要求服务时间 = 1 + (等待时间/要求服务时间)
如果不是都到达再处理,那么还是把地一个先到的处理了

|    | 作业提交 | 时间运行时间 | 在某一时刻响应比                    | 完成时间 | 周转时间 | 带权      |
| J1 |     8:00 |          1.0 | 这时只有该到达完成J1                |     9:00 | 1.0      | 1/1       |
| J2 |     8:50 |         0.50 | J2/J3 J2=1+10/30 J3=1 故完成J2      |     9:30 | 40/60    | 40/60/0.5 |
| J3 |     9:00 |         0.20 | J3/J4 J3=1+30/12 J4=1+20/6 故完成J4 |     9:48 | 48/60    | 48/60/0.2 |
| J4 |     9:10 |         0.10 |                                     |     9:36 | 26/60    | 26/60/0.1 |
#+BEGIN_SRC emacs-lisp
  (/ 40 60 1.0)
  (/ 48 60 1.0)
  (/ 26 60 1.0)
#+END_SRC

-----

*** 在一个请求分页存储管理系统中,一个程序的页面走向为6, 0, 1, 2, 0, 3, 0, 4, 2, 3,分别采用最佳置换算法,先进先出,最近最久未使用算法,完成下列要求.
设分配给该程序的存储块数M=3, 每调进一个新页就发生一次缺页中断.计算各算法的缺页次数和置换次数

最佳置换算法:(OPT)
| order     | 6 | 0 | 1 | 2 | 0 | 3 | 0 | 4 | 2 | 3 |
|           |   |   |   |   |   |   |   |   |   |   |
| M=1       | 6 | 6 | 6 | 2 | 2 | 2 | 2 | 2 | 2 | 2 |
| M=2       |   | 0 | 0 | 0 | 0 | 0 | 0 | 4 | 4 | 4 |
| M=3       |   |   | 1 | 1 | 1 | 3 | 3 | 3 | 3 | 3 |
| interaput | x | x | x | x |   | x |   | x |   |   |
| exchange  |   |   |   | x |   | x |   | x |   |   |
中断6次
置换3次

先进先出算法:(FIFO)
| order     | 6 | 0 | 1 | 2 | 0 | 3 | 0 | 4 | 2 | 3 |
|           |   |   |   |   |   |   |   |   |   |   |
| M=1       | 6 | 6 | 6 | 2 | 2 | 2 | 2 | 4 | 4 | 4 |
| M=2       |   | 0 | 0 | 0 | 0 | 3 | 3 | 3 | 2 | 2 |
| M=3       |   |   | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 3 |
| interaput | x | x | x | x |   | x | x | x | x | x |
| exchange  |   |   |   | x |   | x | x | x | x | x |
中断5次
置换6次

最近最久未使用:(LRU)
| order     | 6 | 0 | 1 | 2 | 0 | 3 | 0 | 4 | 2 | 3 |
|           |   |   |   |   |   |   |   |   |   |   |
| M=1       | 6 | 6 | 6 | 2 | 2 | 2 | 2 | 4 | 4 | 4 |
| M=2       |   | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 3 |
| M=3       |   |   | 1 | 1 | 1 | 3 | 3 | 3 | 2 | 2 |
| interaput | x | x | x | x |   | x |   | x | x | x |
| exchange  |   |   |   | x |   | x |   | x | x | x |

-----

*** 有一间阅览室,有100个座位,读者进入时必须先在一张登记表上登记,该表为每一座位列一表目,包括座号和读者姓名,读者离开时要销掉登记内容,用PV操作描述读者进程同步结构
#+BEGIN_SRC c
  mutex = 1; //互斥信号
  full = 100; //同步信号
  table: array 0 ... ... n-1 of item
  procedure reader;
  begin
      P(full);
      P(mutex);
      Register_name(table);
      V(mutex);
      Reading;
      P(mutex);
      Delete_name(table);
      V(mutex);
      V(full);
  end;

#+END_SRC

*** 如图1所示,系统中有三个进程GET,PRO,PUT,共用两个缓冲BUF1,BUF2.假设BUF1中最多可以存放11个信息,现已放入两个信息,BUF2最多可以存放5个信息.GET进程负责不断地将输入信息送入BUF1中,PRO进程负责从BUF1中取出信息并进行处理,并将处理结果送到BUF2中,PUT进程负责从BUF2中读取结果并输出.试写出正确实现GET,PRO,PUT的同步与互斥算法
(1)用类C语言描述,条理清晰,注释恰当;
(2)信号量原语使用wait,signal,或者PV操作描述
#+BEGIN_SRC c
  int Buf1_Idle = 9;
  int Buf1_Busy = 2;
  int Buf2_Idle = 5;
  int Buf2_Busy = 0;
  int mutex1 = mutex2 = 1;

  void GET(){
      while(1){
          P(Buf1_Idle);
          P(mutex1);
          sendto BUF1;
          V(Buf1_Busy);
          V(mutex1);
      }
  }

  void PRO(){
      while(1){
          P(Buf1_Busy);
          P(mutex1);
          recefrom BUF1;
          V(mutex1);
          V(Buf1_Idle);

          P(Buf2_Idle);
          P(mutex2);
          sendto BUF2;
          V(mutex2);
          V(Buf2_Busy);
      }
  }

  void PUT(){
      while(1){
          P(Buf2_Busy);
          P(mutex2);
          printf(BUF2);
          V(mutex2);
          V(Buf2_Idle);
      }
  }

  int main() {
      Cobegin
          GET(),
          PRO(),
          PUT();
      Coend;
      return 0;
  }
#+END_SRC

-----

*** 假定某在磁盘上,处理访问56号磁道的请求后,现正在70号磁道上读信息,目前有下面的请求访问磁盘磁道的序列
73,68,100,120,60,108,8,50,请写出
(1)用最短寻道时间优先算法(SSTF),列出响应磁道次序,并计算平均寻道长度
68,73,60,50,8,100,108,120
(2+5+13+10+42+92+8+12)/8 = 23
(2)用电梯调度算法,列出响应的磁道次序,并计算平均寻道长度
73,100,108,120,68,60,50,8
(3+27+8+12+52+8+10+42)/8 = 20.25
#+BEGIN_SRC emacs-lisp
(/ (+ 2 5 13 10 42 92 8 12) 8.0)
(/ (+ 3 27 8 12 52 8 10 42) 8.0)
#+END_SRC

-----

*** 什么是进程?什么是线程
?进程与线程有何区别?
(1)进程是具有独立功能程序在某个数据集合上的一次执行过程
(2)线程是进程内一个执行实体或执行单元
(3)进程和线程的区别:
a)不同的进程的地址空间是独立的,而同一进程内的线程共享同一地址空间.一个进程的线程咋另一个进程中是不可见的.
b)在引入线程的操作系统中,进程是资源分配和调度的单位,线程是处理机调度和分配的单位,资源是分配给进程的,线程只拥有很少的资源,因而切换代价比进程切换低

*** 何谓系统调用?它与一般的过程调用有何区别?
从而使用户在自己的程序中可获得OS提供的服务,如打开文件,创建子进程
系统调用与一般的过程调用的区别主要有如下几点:
1)运行在不同的系统状态:一般的调用程序和被调用的程序都运行在相同的状态(系统态或者用户态);而对系统调用,其调用程序是运行在用户态,而被调用程序则运行在系统态
2)通过软中断进入;一般的过程调用可以通过过程调用语句直接由调用过程转向被调用过程;而系统调用则必须通过执行系统调用命令(也称作访管指令),由软中断(或陷入机制)转向相应的系统调用处理程序,同时CPU的执行状态将由用户状态转换为系统态
3)返回问题:一般的过程调用在被调用过程执行完后,将直接返回到调用过程继续执行;对系统调用,如果用抢占方式,则在被调用过程执行完后,必须先对运行的进程做优先权分析,只当调用进程仍具有最高优先权时,才返回到调用进程继续执行否则,将引起重新调度

-----

*** 产生死锁的必要条件有哪些?处理死锁的基本方法有哪些?
(1)产生的必要条件:互斥条件,请求和保持条件,不剥夺条件,环路等待条件
(2)处理的方法:预防死锁,避免死锁,检测死锁,解除死锁

*** 请画出I/O系统层次结构
| 用户层软件   |
| 设备独立性   |
| 设备驱动程序 |
| 中断处理程序 |
| 硬件         |

*** 外存的组织方式,链接组织方式相对连续组织方式,有哪些优点?链接组织方式又可以分为哪两种形式?
(1)消除了外部碎片,故而显著提高了外存空间利用率
(2)对插入,删除和修改记录都非常容易
(3)当文件动态增长时,可以动态地再为它分配盘块,无需事先知道文件大小
分为:显式链接和隐式链接


*** 文件系统中对目录管理有那些要求
(1)实现"按名存取"
(2)提高对目录的检索速度
(3)文件共享
(4)允许文件重名

-----

*** 在采用分页存储管理系统中,页面大小为1K,一个三页长的进程,其页表如下

| 页号 | 页框号 |
|    0 |      2 |
|    1 |      3 |
|    2 |      8 |
请分别计算逻辑地址为100和2500的两条指令的物理地址

100:
INT(100/1024) = 0
物理地址:
2 * 1024 + 100 = 2148

2500
INT(2500/1024) = 2
2500 - 1024 * 2 = 452
物理地址:
8 * 1024 + 452 = 8644

-----

*** 在一个请求分页系统中有一用户作业,它要一次访问字的地址序列是:
114,218,120,46,158,440,102,323,432,260,360,167
现在分配给该作业耳朵主存一共300字,页的大小为100字,试问采用最佳置换算法(OPT),最近最近未使用算法(LRU),发生页面置换的次数是多少?

首先将其对换为页面
1,2,1,0,1,4,1,3,4,2,3,1

OPT:
|           | 1 | 2 | 1 | 0 | 1 | 4 | 1 | 3 | 4 | 2 | 3 | 1 |
|           |   |   |   |   |   |   |   |   |   |   |   |   |
| M=1       | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 3 | 3 | 3 | 3 | 1 |
| M=2       |   | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 | 2 |
| M=3       |   |   |   | 0 | 0 | 4 | 4 | 4 | 4 | 4 | 4 | 4 |
| interaput | x | x |   | x |   | x |   | x |   |   |   | x |
| exchange  |   |   |   |   |   | x |   | x |   |   |   | x |
发生3次置换

LRU:

|           | 1 | 2 | 1 | 0 | 1 | 4 | 1 | 3 | 4 | 2 | 3 | 1 |
|           |   |   |   |   |   |   |   |   |   |   |   |   |
| M=1       | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 2 | 2 | 2 |
| M=2       |   | 2 | 2 | 2 | 2 | 4 | 4 | 4 | 4 | 4 | 4 | 1 |
| M=3       |   |   |   | 0 | 0 | 0 | 0 | 3 | 3 | 3 | 3 | 3 |
| interaput | x | x |   | x |   | x |   | x |   | x |   | x |
| exchange  |   |   |   |   |   | x |   | x |   | x |   | x |
发生了4次置换

-----

*** 假定在某磁盘上处理了访问49号磁道的请求后,现在正在69号磁道上读信息,目前有下面的请求访问磁盘磁道的序列
74,68,100,120,60,108,8,41
(1)用最短寻道时间优先(SSTF),列出响应磁道次序,并计算平均寻道长度
68,74,60,41,8,100,108,120
(1+6+14+19+33+92+8+12)/8 = 23.125

(2)用电梯调度算法,列出磁道次序,并计算平均寻道长度
74,100,108,120,68,60,41,8
(5+26+8+12+52+8+19+33)/8 = 20.375

#+BEGIN_SRC emacs-lisp
(/ (+ 1 6 14 19 33 92 8 12) 8.0)
(/ (+ 5 26 8 12 52 8 19 33) 8.0)

#+END_SRC

-----

*** 某个寺庙,有小和尚,老和尚若干.寺庙里有一水缸,供取水喝.水缸可以容纳30桶水,每次入水,取水仅为一桶,不可同时进行.水取自同一井中,水井只能一个桶取水.水桶个数为5个,请用wait,signl信号量给出老和尚和小和尚并发过程,下面给出了程序框架,请完善信号量的定义并赋予初始值

#+BEGIN_SRC c
  semaphore
  mutex_jar = 1, mutex_wel = 1, empty = 30, full = 5, bucket = 5;

  void 小和尚(){
      while(1){
          wait(empty);
          wait(bucket);
          提桶到井边;
          wait(mutex_wel);
          把桶放入井中取水;
          signal(mutex_wel);
          提着水进寺庙;
          wait(mutex_jar);
          把水倒入缸中;
          signal(mutex_jar);
          signal(bucket);
          signal(full);
      }
  }

  void 老和尚(){
      while(1){
          wait(full);
          wait(bucket);
          wait(mutex_jar);
          用桶到缸中取水饮用;
          signal(mutex_jar);
          signal(bucket);
          signal(empty);
      }
  }

  void main(){
      cobegin
          小和尚(),
          老和尚();
      coend
  }
#+END_SRC



* 各种算法知识点小结

** FAT12的FAT表大小计算


** 银行家算法
由available的最大值,(随意满足)满足客户Need后回收(其allocation),拥有更大avaliable后再去满足下一位(任一)客户直到完成
只要最后能完成就是一个安全序列

根据题目描述提出请求的就是下一个满足对象


** 最佳置换算法
由需要发生的时间来决定淘汰那个,比如
7,0,1,2,0,3,0,4,2,3,2,1,2,0,1,7,0,1
| 现在内存 |                                                                              |
| 7 0 1    | 现在要装入2发生缺页中断                                                      |
| 2 0 1    | 因为7在第18次才用到,所以决定淘汰7 ,但是实际情况中,你并不知道接下来的使用情况 |
|          |                                                                              |
|          |                                                                              |


** 记录型信号量
申请资源就s--,如果s= -1 就表示有一个进程在等待

那么我们说n个进程使用同一个共享变量,允许m (m<n)个可以同时访问,那么信号量的范围是

m,m-1,....,0,-1,m-n

表示有 n-m个进程在等待


** 死锁
- 避免死锁
  - 银行家算法
- 预防死锁
  - 破坏必要条件


** 杂
位示图: 是操作系统中,一种管理空闲存储的方法

虚拟: 把物理实体变为若干个逻辑上的对应物

假脱机: 物理I/O 虚拟多个逻辑I/O

线程: cpu调度最小单位

挂起: 终端用户请求,父进程请求,负荷调节需要,操作系统需要

整形信号量: 盲等现象

四条基本准则: 空闲让进,忙则等待,有限等待,让权等待

引起饥饿现象的: SSTF

避免饥饿现象: SCAN

信号量缺陷: 虽然是方便的同步机制,每个进程都需要一个wait,signal,同步操作分散在各个进程,给系统管理带来麻烦,因同步操作使用不当导致死锁
解决方案引进管程

磁盘是块设备

打印机是中速设备

文件按逻辑:
无结构 流式文件
有结构 记录文件



* 疑似考点


** 名词解释

*** 临界资源

#+BEGIN_SRC
在一段时间只能被一个进程访问的资源
许多硬件资源,例如打印机,磁带机
一部分软件资源
进程之间应采用互斥的方式来实现这种资源的共享
生产者消费者问题:
#+END_SRC

*** 临界区

#+BEGIN_SRC
每个进程中访问临界资源的那段代码称为临界区

保证每个进程互斥地进入临界区,便可以实现诸进程对临界资源的互斥访问

进入临界区
对临界资源检查,是否正在被访问
未被访问则允许进入临界区访问
已被访问则不允许进入临界区

该检查代码称为进入区

#+END_SRC
| 进入区 |
| 临界区 |
| 退出区 |
| 剩余区 |



*** 死锁

**** 资源问题
1.
   - 可重用性资源
   - 可消耗性资源
2.
   - 可抢占性资源
   - 不可抢占性资源

**** 死锁

***** 产生
1. 竞争不可抢占性资源
2. 竞争可消耗资源
3. 进程推进顺序不当

***** 定义

每个进程所等待的事件都是其他进程释放其所占有资源.但由于这些程序都已无法运行,它们谁也不释放资源,致没有任何一个进程可以被唤醒.这组进程只能无限期的等待下去

如果一组进程的每一个进程都在等待仅由该组进程的其他进程才能引发的事件,那么该组进程死锁

***** 必要条件
1. 互斥条件
   - 进程对所分配到的资源进行排它性使用,即在一段时间内,某资源只能被一个进程占用.如果此时还有其他进程请求,则请求进程只能等待,直到占有的进程释放
2. 请求和保持条件
   - 进程已经保持至少一个资源,但又提出新的资源请求,而该资源已被其他进程所占有,此时请求进程阻塞,但对自己已获得的资源保持不放
4. 不可抢占条件
   - 进程已获得的资源在未使用前不能被抢占,只能在进程使用完时由自己释放
5. 循环等待条件
   - 发生死锁时, 必存在进程-资源,循环链,P0等P1,P1等P2....Pn等P0

***** 处理方法
1. 预防死锁
   - 事先设置某些限制,去破坏四个必要条件的一个或几个来预防死锁
2. 避免死锁
   - 而是在资源动态分配的过程中,用某种方法防止系统进入不安全状态
3. 检测死锁
   - 检测到发生死锁时采取某种措施,把进程从死锁解脱出来
4. 解除死锁
   - 发生死锁时,采取相应操作使其从死锁解脱出来,常用撤销一些进程,回收他们资源,将它们分配给已处于阻塞的进程

***** 预防死锁
1. 破坏请求保持条件
   1. 第一种协议
      所有进程在开始运行之前,必须一次性的申请整个运行过程所需要的全部资源.此时系统有资源分配给某进程,便把所以资源分配给该资源,只要有一种资源不够分配给该进程,所有资源都不分配给它
   2. 第二种协议
      允许一个进程,满足初期资源后便开始运行,运行过程中逐步释放已被分配的,且用完的全部资源,再申请所需的新资源.
2. 破坏不可抢占条件
   一个保持了某些不可释放资源的进程,在请求新资源时,它必须释放所有保持的资源
3. 破坏循环等待条件
   把所有资源线性排序后,每个进程需要按照序号递增的顺序请求资源,请求Ri后的资源后只能申请Rj > Ri的资源,如果要申请更低只能全部释放从来

***** 避免死锁
1. 安全状态
   处于安全状态的系统,可避免死锁.处于不安全状态,则可能进入死锁

   允许进程动态的申请资源,但系统在进行资源分配前,先计算资源分配的安全性,若不会进入不安全状态则分配,否则等待
2. 银行家算法

***** 死锁的检测
1. 保存有关资源请求和分配信息
2. 提供一种算法,它利用这些信息来检测是否进入死锁状态


- 资源分配图
- 死锁定理
- 死锁检测中的数据结构

***** 死锁解除

1. 终止进程
   1. 终止所有
   2. 逐个终止

2. 付出代价最小的死锁解除算法
   先计算出一些代价,再用这些代价来衡量终止的可行性,从中选择代价最小的和



*** 装入和链接

**** 装入
1. 绝对装入方式
   程序编译后产生绝对地址,装入的程序中的相对地址与实际内存地址完全相同
2. 可重定位装入方式
   根据内存情况将装入模块装入到内存适当位置,地址变换过程在程序装入时一次性完成,故称静态重定位
3. 动态运行时装入
   装入模块装入内存后,并不立即把装入模块中的逻辑地址转换为物理地址,而是把这种地址转换推迟到程序真正要执行


**** 链接
1. 静态链接
2. 装入时动态链接
   边装入,边链接

   但是会把所以模块装入
3. 运行时动态链接
   某些模块的装入推迟到程序执行时


*** 紧凑
将内存中所有作业进行移动,使他们全都相邻接.这样把分散的多个空闲小分区拼接成一个大分区,可将一个作业装入.
把多个小分区拼接成一个大分区的方法

*** 虚拟存储器
1. 多次性
   无需作业运行时全部装入内存,而是运行分成多次调入内存
2. 对换性
   无需作业运行时一直驻留内存,允许作业运行过程进行对换,换出
3. 虚拟性
   能够从逻辑上扩充内存容量

**** 实现方法
1. 分页请求系统
   - 硬件支持
     1. 请求分页的页表机制
     2. 缺页中断机构
     3. 地址变换机构
   - 实现请求分页的软件
   -

2. 请求分段系统
   - 硬件支持
     1. 请求分段的段表机制
     2. 缺段中断结构
     3. 地址变换机构

   - 软件支持


*** 抖动
人们希望系统运行更多进程,增加程序度,提高处理机利用率.但是出现CPU利用率趋于0的情况就是发生了抖动

**** 产生抖动原因

同时在系统中运行的进程太多,因此分配给每个进程的物理块太少,不能满足进程正常运行的基本需要,致使每个进程在运行时,频繁的出现缺页,必须请求系统调入所缺页.使得系统中排队等待页面调入/调出的进程数目增加,对磁盘有效访问时间急剧增加,造成每个进程大部分时间都处于页面的换入换出
几乎不能工作,导致CPU利用率趋于0

我们称此时为抖动

*** 工作集
**** 基本概念
基于程序运行时局部性原理得知,程序在运行期间,对页面的访问是不均等的,在一段时间内仅局限于较少的页面,在另一段时间,又可能局限另一些较少的页面进行访问.
这些页面被称为活跃页面.如果能预知程序在某段时间间隔内要访问哪些页面,并将它们调入内存,将会大大降低缺页率,从而显著的提高处理机利用率.

**** 定义
所谓工作集,是指在某段时间间隔内,进程实际要访问页面的集合

*** 块设备
所谓块设备,是指数据的存取传输都是以数据块为单位的设备.

典型有 磁盘

磁盘设备的I/O常采用DMA

*** 设备独立性
(1)设备独立性即在应用程序中所使用的设备,不局限于使用某个具体物理设备
(2)应用程序用逻辑设备名称来请求使用某类设备.系统在执行时,使用物理设备名称


* 玄学内容

** 玄学简答题
*** 文件系统中对目录管理有哪些需求?
1.实现"按名存取"
2.提高对目录的检索速度
3.文件共享
4.允许文件重名


** 玄学选择题
#+BEGIN_SRC

1．（ D      ）不是基本的操作系统。
A、批处理操作系统       B、分时操作系统
C、实时操作系统         D、网络操作系统

2．（ A     ）不是分时系统的基本特征：
A、同时性       B、独立性
C、实时性       D、交互性

3．进程所请求的一次打印输出结束后，将使进程状态从（  D    ）
      A、运行态变为就绪态       B、运行态变为等待态
C、就绪态变为运行态       D、等待态变为就绪态

4．采用动态重定位方式装入的作业，在执行中允许（ C     ）将其移动。
      A、用户有条件地    	   B、用户无条件地
C、操作系统有条件地      D、操作系统无条件地

5．分页式存储管理中，地址转换工作是由（ A     ）完成的。
      A、硬件 		      B、地址转换程序
C、用户程序 	             D、装入程序

6．如果允许不同用户的文件可以具有相同的文件名，通常采用（ D     ）来保证按名存取的安全。
      A、重名翻译机构	      B、建立索引表
C、建立指针 		      D、多级目录结构

7．对记录式文件，操作系统为用户存取文件信息的最小单位是（C   ）。
      A、字符 		      B、数据项
C、记录 		      D、文件

8．为了提高设备分配的灵活性，用户申请设备时应指定（ A     ）号。
      A、设备类相对 	      B、设备类绝对
C、相对 		          D、绝对

9．一作业进入内存后，则所属该作业的进程初始时处于（  C    ）状态。
      A、运行 		      B、等待
C、就绪 		      D、收容

10．共享变量是指（ D     ）访问的变量。
      A、只能被系统进程       B、只能被多个进程互斥
C、只能被用户进程       D、可被多个进程

11．临界区是指并发进程中访问共享变量的（ D     ）段。
      A、管理信息   		  B、信息存储
C、数据 		          D、程序

12．若系统中有五台绘图仪，有多个进程均需要使用两台，规定每个进程一次仅允许申请一台，则至多允许（ D     ）个进程参于竞争，而不会发生死锁。
      A、5 		      B、2
C、3 		      D、4

13．产生系统死锁的原因可能是由于（  C    ）。
      A、进程释放资源 			      B、一个进程进入死循环
C、多个进程竞争，资源出现了循环等待      D、多个进程竞争共享型设备

14．地址重定位的结果是得到（D ）
A． 源程序
B． 编译程序
C． 目标程序
D． 执行程序

15．为了对文件系统中的文件进行安全管理，任何一个用户在进入系统时都必须进行注册，
这一级管理是＿＿＿＿安全管理。（A ）
A． 系统级
B． 用户级
C． 目录级
D． 文件级

16．运行时间最短的作业被优先调度，这种企业调度算法是（C ）
A． 优先级调度
B． 响应比高者优先
C． 短作业优先
D． 先来先服务

17．产生死锁的主要原因是进程运行推进的顺序不合适（D ）
A． 系统资源不足和系统中的进程太多
B． 资源的独占性和系统中的进程太多
C． 进程调度不当和资源的独占性
D． 资源分配不当和系统资源不足

18.  实时操作系统追求的目标是（ C  ）。
A.高吞吐率       B.充分利用内存       C. 快速响应 D. 减少系统开销

19.  操作系统是为了提高计算机的[1]B和方便用户使用计算机而配置的基本软件。它负责管理计算机系统中的[2]C，
其中包括[3]F，[4]A，外部设备和系统中的数据。操作系统中的[3]F管理部分负责对进程进行管理。操作系统对系统中的数据进行管理的部分通常叫做[5]B。
供选择的答案：
[1]    A、速度       B、利用率       C、灵活性 D、兼容性
[2]    A、程序       B、功能  C、资源   D、进程
[3] F[4]A     A、主存储器    B、虚拟存储器  C、运算器
  D、控制器      E、微处理器    F、处理机
[5]      A、数据库系统  B、文件系统    C、检索系统
  D、数据库      E、数据存储系统       F、数据结构
  G、数据库管理系统

20.  批处理系统的主要缺点是（ B   ）。
A.CPU的利用率不高       B.失去了交互性
C.不具备并行性     D.以上都不是

21.     如果文件系统中有两个文件重名，不应采用（ A  ）。
A.一级目录结构      B.树型目录结构
C.二级目录结构      D.A和C

22.     树型目录结构的第一级称为目录树的（  B   ）。
A.分支节点 B.根节点   C.叶节点   D.终节点

23、  虚拟内存的容量只受（  D ）的限制。
A.物理内存的大小           B.磁盘空间的大小
C.数据存放的实际地址       D.计算机地址位数

24、分段管理提供（ 2  ）维的地址结构。
A.1            B.2  C.3   D.4

25、（  D  ）实现了段式、页式两种存储方式的优势互补。
A.请求分页管理                  B.可变式分区管理
C.段式管理           D.段页式管理

26、以下存储管理技术中，支持虚拟存储器的技术是（C  ）。
A．动态分区法    B．可重定位分区法    C．请求分页技术    D．对换技术

27、下列（ D   ）存储管理方式能使存储碎片尽可能少，而且使内存利用率较高。
A.固定分区             B.可变分区
C.分页管理             D.段页式管理

28、操作系统中采用缓冲技术的目的是为了增强系统（ D    ）的能力。
A.串行操作          B. 控制操作
C.重执操作          D.并行操作

29.      B     是指从作业进入系统到作业完成所经过的时间间隔；     D    是从作业进入后备队列起，到被调度程序选中时的时间间隔。
A：响应时间；			B：周转时间；
C：运行时间；			D：等待时间；
F：触发时间。

30. 产生死锁的四个必要条件是互斥条件和  (1) C  ，不剥夺条件和  (2)B   。
(1)    A：请求和阻塞条件；		 B：请求和释放条件；
C：请求和保持条件；		 D：释放和阻塞条件；
E：释放和请求条件。
(2)   A：线性增长条件；			 B：环路条件；
C：有序请求条件；			 D：无序请求条件。

31. 在      A     中，要求空闲分区按空闲区地址递增顺序链接成空闲分区链；在             _C___中是按空闲区大小递增顺序形成空闲分区链；
在    B      中，是按空闲区大小递减的顺序形成空闲分区链。
A：首次适应算法；		B：最坏适应算法；
C：最佳适应算法；		D：循环首次适应算法。

32．在 UNIX 系统中获取帮助信息的命令为      B     。
A：help		B：man		C：cat

33．CPU的调度分为高级、中级和低级三种，其中低级调度是指    C         调度。
A：作业		B：交换		C：进程

34．在请求调页中可采用多种置换算法，其中LRU是      B        置换算法。
A：最佳			B：最近最久未用
C：最近未用			D：最少使用

35．对打印机进行I/O控制时，通常采用      B          方式；对硬盘的I/O控制采用           C      方式。
A：程序直接控制			B：中断驱动
C：DMA			      D：通道

36．在 UNIX 系统中采用的页面置换算法是         A            。
A：CLOCK				B：OPT
C：NRU			      D：LRU

37．在磁盘调度算法中，选择与当前磁头移动方向一致、磁头单向移动且距离最近的进程的算法为          C         。
A：FIFO				B：SCAN
C：CSCAN			      D：FSCAN

38．在 UNIX 系统中的 mv 命令表示        D             。
A：删除文件				B：移动文件或对文件换名
C：复制文件

39.  操作系统是计算机系统的核心软件。按功能特征的不同，可把操作系统分为[1]、[2]、[3]、网络操作系统和分布式操作系统基本类型。其中[1]的主要目标是提高系统的吞吐率和效率，而[2]是一旦有处理请求和要求处理的数据时，CPU就应该立即处理该数据并将结果及时送回，例如[4]等。
供选择的答案：
[1]B[2]E[3]C
A、  单用户系统      B、批处理系统       C、分时系统
D、微机操作系统     E、实时系统
[4] D
A、计算机激光照排系统   B、办公自动化系统
C、计算机辅助设计系统   D、航空订票系统

40.  现代操作系统的两个基本特征是（   C  ） 和资源共享。
A.多道程序设计   B. 中断处理
C.程序的并发执行 D. 实现分时与实时处理

41.  以下（C  ）项功能不是操作系统具备的主要功能。
A．内存管理      B．中断处理       C．文档编辑       D．CPU调度

42.  批处理系统的主要缺点是（ B   ）。
A.CPU的利用率不高       B.失去了交互性
C.不具备并行性     D.以上都不是

43.  引入多道程序的目的在于（  A ）。
A.    充分利用CPU，减少CPU等待时间
B.     提高实时响应速度
C.    有利于代码共享，减少主、辅存信息交换量
充分利用存储器

44.     在分时系统中，时间片一定，（ B   ），响应时间越长。
A.内存越多    B.用户数越多
C.后备队列           D.用户数越少

45.     系统调用是由操作系统提供的内部调用，它（  B  ）。
A.直接通过键盘交互方式使用
B. 只能通过用户程序间接使用
C.是命令接口中的命令使用
D. 与系统的命令一样

46.     为了对紧急进程或重要进程进行调度，调度算法应采用（  B  ）。
A.先进先出调度算法    B. 优先数法
C.最短作业优先调度      D. 定时轮转法

47、若一个系统内存有64MB，处理器是32位地址，则它的虚拟地址空间为（ B   ）字节。
A.2GB          B.4GB      C.100KB                 D.64MB

48．外存（如磁盘）上存放的程序和数据（B  ）。
A．可由CPU 			        B．必须在CPU访问之前移入内存
C．是必须由文件系统管理的        D．必须由进程调度程序管理

49、一个40G的硬盘，块的大小为１Ｋ，其FAT要占（　C　　）空间。
A.100M          B.120M
C.140M          D.160M

50.     文件系统在创建一个文件时，为它建立一个（ A   ）。
A.文件目录          B.目录文件
C.逻辑结构   D.逻辑空间

51.     文件的存储方法依赖于（  C  ）。
A.文件的物理结构    B.存放文件的存储设备的特性
C.A和B     D.文件的逻辑

52.     使用绝对路径名访问文件是从（  C ）开始按目录结构访问某个文件。
A.当前目录 B.用户主目录      C.根目录   D.父目录

53.     目录文件所存放的信息是（ D   ）。
A.某一文件存放的数据信息
B. 某一文件的文件目录
C.该目录中所有数据文件目录
D. 该目录中所有子目录文件和数据文件的目录

54.     由字符序列组成，文件内的信息不再划分结构，这是指（A   ）。
A.流式文件 B. 记录式文件
C.顺序文件   D.有序文件

55.     数据库文件的逻辑结构形式是（ C  ）。
A.字符流式文件 B. 档案文件
C.记录式文件   D.只读文件

56.     逻辑文件是（  B  ）的文件组织形式。
A.在外部设备上 B.从用户观点看
C.虚拟存储     D.目录

57、  存储管理的目的是（  C  ）。
A.方便用户           B.提高内存利用率
C.方便用户和提高内存利用率      D.增加内存实际容量

58、存储分配解决多道作业地址空间的划分问题。为了实现静态和动态存储分配，需采用地址重定位，即把[1][2]，静态重定位由[3]实现，动态重定位由[4]实现。
供选择的答案：
[1]C、[2] D  A 页面地址        B 段地址       C 逻辑地址
D 物理地址        E 外存地址     F 设备地址
[3]D、[4] A  A 硬件地址变换机构      B 执行程序       C 汇编程序
D 连接装入程序          E 调试程序       F 编译程序       G 解释程序
（说明：汇编程序、解释程序、编译程序的作用是将源程序变为机器语言指令；调试程序是进行程序调试的一种工具。执行程序是可被计算机直接执行的机器代码程序。）

59、在请求页式存储管理中，若所需页面不在内存中，则会引起（ D ）。
A.输入输出中断         B. 时钟中断
C.越界中断             D. 缺页中断；

60、若处理器有32位地址，则它的虚拟地址空间为（  B  ）字节。
A.2GB          B.4GB            C.100KB D.640KB

61、虚拟存储技术是（ B ）。
A.补充内存物理空间的技术              B.补充相对地址空间的技术
C.扩充外存空间的技术       D.扩充输入输出缓冲区的技术

62、  外存（如磁盘）上存放的程序和数据（ B ）。
A．可由CPU         B．必须在CPU访问之前移入内存
C．是必须由文件系统管理的    D．必须由进程调度程序管理

63、段页式存储管理汲取了页式管理和段式管理的长处，其实现原理结合了页式和段式管理的基本思想，即（  B   ）。
A、用分段方法来分配和管理物理存储空间，用分页方法来管理用户地址空间。
B、用分段方法来分配和管理用户地址空间，用分页方法来管理物理存储空间。
C、用分段方法来分配和管理主存空间，用分页方法来管理辅存空间。
D、用分段方法来分配和管理辅存空间，用分页方法来管理主存空间。

64、（     C    ）存储管理支持多道程序设计，算法简单，但存储碎片多。
A.段式                  B.页式
C.固定分区   D.段页式

65、（   C ）存储管理方式提供一维地址结构。
A.固定分区         B.分段
C.分页             D.分段和段页式

66、在请求分页系统中，LRU算法是指（  B ）。
A、最早进入内存的页先淘汰
B、近期最长时间以来没被访问的页先淘汰
C、近期被访问次数最少的页先淘汰
D、以后再也不用的也先淘汰

67、请求分页存储管理中，若把页面尺寸增加一倍，在程序顺序执行时，则一般缺页中断次数会（  B）。
A．增加     B．减少     C．不变     D．可能增加也可能减少
68、碎片现象的存在使得（  A  ）。
A.内存空间利用率降低        B. 内存空间利用率提高
C.内存空间利用率得以改善    D. 内存空间利用率不影响

69、当内存碎片容量大于某一作业所申请的内存容量时，（ D  ）。
A、可以为这一作业分配内存
B、不可以为这一作业分配内存
C、拼接后，可以为这一作业分配内存
D、一定能够为这一作业分配内存

70、设备管理的目的是为了合理地利用外部设备和[1]，设备按照信息的传递特性可分为[2]和[3]。设备管理的主要程序之一是设备分配程序，当进程请求在内存和外设之间传送信息时，设备分配程序分配设备的过程通常是[4]。
供选择的答案：
C[1]： A、提高CPU利用率   B、提供接口    C、方便用户      D、实现虚拟设备
A[2]： A、块设备           B、存储设备    C、独立设备      D、虚拟设备
D[3]： A、共享设备         B、输入输出设备    C、系统设备      D、字符设备
A[4]： A、先分配设备，再分配控制器，最后分配通道
B、先分配控制器，再分配设备，最后分配通道
C、先分配通道，再分配设备，最后分配控制器
D、先分配通道，再分配控制器，最后分配设备

71、通道是一种（ C   ）。
A.I/O端口          B.数据通道
C.I/O专用处理机    D.软件工具

72、缓冲技术用于（ A  ）。
A、提高主机和设备交换信息的速度
B、提供主、辅存接口
C、提高设备利用率
D、扩充相对地址空间

73、采用SPOOLing技术的目的是（ A  ）。
A.提高独占设备的利用率     B.提高主机效率
C.减轻用户编程负担         D.提高程序的运行速度

74、采用假脱机技术的目的是[1]。假脱机技术是将输入输出控制工作大部分交由相应的通道来承担，利用磁盘作为后援存储器，实现了外设同时联机操作，使得[2]成为[3]，减少了对频繁使用外设的压力，但假脱机技术一般不适用于[4]。
供选择的答案：
A[1]：  A、提高外设和主机的利用率        B、提高内存和主机效率
       C、减轻用户编程负担   D、提高程序的运行速度
[2]C[3]D： A、块设备      B、字符设备      C、独占设备      D、虚拟设备
A[4]：    A、分时系统         B、多道批处理系统  
         C、网络操作系统     D、多处理机系统

75、在操作系统中，用户在使用I/O设备时，通常采用（   B     ）。
A.物理设备名         B.逻辑设备名
C.虚拟设备名         D.设备牌号

76. 操作系统有多种类型：允许多个用户以交互方式使用计算机的操作系统，称为  B   ；允许多用户将若干个作业提交给计算机系统集中处理的操作系统，称为   A   ；
在                 C的控制下，计算机系统能及时处理由过程控制反馈的数据，并作出响应；在IBM－PC机上的操作系统称为  D     。
A：批处理操作系统；  B：分时操作系统； C：实时操作系统；D：微机操作系统；E：多处理机操作系统； F：分布式操作系统

77. 我们如果为每一个作业只建立一个进程，则为了照顾短作业用户，应采用  B  ；为照顾紧急作业用户，
应采用   E   ，为能实现人机交互作用应采用 C    ，而能使短作业，长作业及交互作业用户都比较满意时，应采用  D    。
A： FCFS调度算法；B：短作业优先调度算法；C：时间片轮转法；D：多级反馈队列调度算法；E：基于优先权的剥夺调度算法；F：响应比优先算法。

78. 产生死锁的基本原因是  (1)  和  (2)  。
B(1) A：资源分配不当；B：系统资源不足；C：作业调度不当；D：资源的独占性。
A(2) A：进程推进顺序非法；B：进程调度不当；C：系统中进程太多；D：CPU运行太快。

79. 通道是一种特殊的  (1)  ，具有  (2)  能力。
C(1) A：I /O 设备；B：设备控制器；C：处理机；D：I / O控制器。
A(2) A：执行 I / O指令集；B：执行CPU 指令集；C：传输I / O 命令；D：运行I / O进程。

80. 静态重定位是在作业的 B    中进行的，动态重定位是在作业的   D  中进行的。
A：编译过程；B：装入过程；C：修改过程；D：执行过程。

81. 在存取文件时，如果是利用给定的记录键值对链表或线性表进行检索，以找到指定记录的物理地址，
则上述文件分别称为  B   或  C    ；如果可根据给定的记录健值直接获得指定记录物理地址，则把这种文件称为   D   。
A：顺序文件；B：串联文件；C：索引文件；D：直接文件。

82. 文件系统最基本的目标是 A   ，它主要是通过目录管理功能实现的，文件系统所追求的最重要目标是  D   。
A：按名存取；B：文件共享；C：文件保护；D：提高对文件的存取速度；E：提高I / O速度；F：提高存储空间的利用率。

83. 在设备管理中为了提高I/O速度和设备利用率，是通过  B     功能实现的。
A：设备分配   B：缓冲管理    C：设备独立性    D：虚拟设备
C

84．在UNIX 系统中对空闲磁盘空间管理的方法是   C       。
A：位示图   B：空闲空间链    C：成组链接法    D：空闲表

85．实现虚拟存储器最关键的技术是      C      。
A：内存分配   B：置换算法    C：请求调页(段)    D：对换空间管理

86 .我们把在一段时间内，只允许一个进程访问的资源，称为临界资源，因此，我们可以得出下列论述，正确的论述为   D  。
A：对临界资源是不能实现资源共享的。
B：只要能使程序并发执行，这些并发执行的程序便可对临界资源实现共享。
C：为临界资源配上相应的设备控制块后，便能被共享。
D：对临界资源，应采取互斥访问方式，来实现共享。

87. 对于记录型信号量，在执行一次P操作时，信号量的值应当  C    ；在执行V操作时，信号量的值应当    B   。
A：不变；   B：加1；  C：减1；  D：加指定数值；  E：减指定数值。

88．在动态分区式内存管理中，倾向于优先使用低地址部分空闲区的算法是   C     ；
能使内存空间中空闲区分布较均匀的算法是    D     ；每次分配时把既能满足要求，又是最小的空闲区分配给进程的算法是   A    。
A：最佳适应算法；     B：最坏适应算法；
C：首次适应算法；     D：循环适应算法；

89. 在回收内存时可能出现下述四种情况：
(1) 释放区与插入点前一分区F1相邻接，此时应  C   ；
(2) 释放区与插入点的后一分区F2相邻接，此时应   D    ；
(3) 释放区不与F1和F2相邻接，此时应   A    。
A：为回收区建立一分区表项，填上分区的大下和始址；
B：以F1分区的表项作为新表项且不做任何改变；
C：以F1分区的表项作为新表项，修改新表项的大小；
D：以F2分区的表项作为新表项，同时修改新表项的大小和始址。
E：以F2分区的表项作为新表项，同时修改新表项的始址。
90. 产生死锁的四个必要条件是互斥条件和  (1)   ，不剥夺条件和  (2)   。
C(1) A：请求和阻塞条件； B：请求和释放条件；C：请求和保持条件；D：释放和阻塞条件；E：释放和请求条件。
B(2) A：线性增长条件；B：环路条件；C：有序请求条件；D：无序请求条件。

91. 按逻辑结构可把文件分为   E    和   F    两类。
A：读，写文件；B：只读文件；C：索引文件；D：链式文件；E：记录式文件；F：流式文件。

92．利用基本文件目录法实现文件共享，文件系统必须设置一个（1） C    ，每个用户都应具有一个  （2）  B      。
（1） A：系统文件目录  B：主目录  C：基本文件目录  D：根目录
（2） A：用户文件目录  B：符号目录  C：基本文件目录  D：当前目录

93．在树型目录结构中，对某文件的首次访问通常都采用     C      ，文件被打开后，对文件的访问采用     D        。
A：文件符号名； 			 	B：从根目录开始的路径名；
C：从当前目录开始的路径名；		D：用户文件描述符

94. 在UNIX系统中，复制文件采用的命令为    A        。
A：cp  		B：mv		C：rm		D：copy

95．假定磁盘的大小为1K，对于1.2MB的软盘，FAT需占用 （1）      的存储空间；对于100MB的硬盘，FAT需占用 （2）       的存储空间。
C（1）A：1KB	B：1.5KB		C：1.8KB		D：2.4KB
D（2）A：100KB	B：150KB		C：200KB		D：250KB

96. 关于操作系统的叙述    D         是不正确的。
A．“管理资源的程序”
B．“管理用户程序执行的程序”
C．“能使系统资源提高效率的程序”
D．“能方便用户编程的程序”

97．对于一个文件的访问，常由  A          共同限制。
A． 用户访问权限和文件属性		B．用户访问权限和文件优先级
C． 优先级和文件属性				D．	文件属性和口令

98.一作业8：00到达系统，估计运行时间为1小时，若10：00开始执行该作业，其响应比是      C      。
A.2　							B.1　
C.3　							D.0.5

99.在动态分区分配方案中，某一作业完成后，系统收回其主存空间，并与相邻空闲区合并，为此需修改空闲区表，造成空闲区数减1的情况是  D            。
A.无上邻空闲区，也无下邻空闲区　　
B.有上邻空闲区，但无下邻空闲区　　
C.有下邻空闲区，但无上邻空闲区　　
D.有上邻空闲区，也有下邻空闲区

100．如果进程需要读取磁盘上的多个连续的数据块， D      数据传送方式的效率最高。
A．程序直接控制方式      B．中断控制方式
C．DMA方式		        D．通道方式

101．使用文件之前必须先     B   文件。
A． 命名      				    B． 打开
C． 建立 		 	 			    D． 备份

102．若干个等待访问磁盘者依次要访问的磁道为20，44，40，4，80，12，76，当前磁头位于40号柱面，若用最短寻道时间优先磁盘调度算法，
则访问序列为：        B         ；若用扫描算法（当前磁头移动的方向为磁道递增），则访问序列为：       C          。
A． 20，44，40，4，80，12，76
B． 40，44，20，12，4，76，80
C． 40，44，76，80，20，12，4
D． 40，44，76，80，4，12，20

103.如果一个磁盘的容量为40G，盘块的大小为4K，那么该磁盘的FAT大小为：    C       。
A． 20M    	    			  	B． 25M
C． 30M			 			        D． 35M

104． 在循环首次适应算法中，要求空闲分区按  A      顺序链接成空闲分区链；在最佳适应算法中是按   C     顺序形成空闲分区链。
A．空闲区首址递增；
B．空闲区首址递减；
C．空闲区大小递增；
D．空闲区大小递减。
#+END_SRC
